# Generated by Django 5.2.6 on 2025-09-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(unique=True)),
                ('password', models.EmailField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=50)),
            ],
        ),
    ]
